### ISSUE TITLE
Andoid Build Fail

### ISSUE THREAD

**Issue by QasimJaffry** [AgoraIO-Community/react-native-agora#295]
Hi. I keep getting this error when I run my app using npx react-native run-android

 Error: Unable to resolve module `./AgoraView.native` from `node_modules\react-native-agora\lib\index.js`:

None of these files exist:
  * node_modules\react-native-agora\lib\AgoraView.native(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules\react-native-agora\lib\AgoraView.native\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (D:\React Native\Pukaar-Community-Application\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (D:\React Native\Pukaar-Community-Application\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (D:\React Native\Pukaar-Community-Application\node_modules\metro\src\node-haste\DependencyGraph.js:287:16)
    at Object.resolve (D:\React Native\Pukaar-Community-Application\node_modules\metro\src\lib\transformHelpers.js:267:42)
    at D:\React Native\Pukaar-Community-Application\node_modules\metro\src\DeltaBundler\traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (D:\React Native\Pukaar-Community-Application\node_modules\metro\src\DeltaBundler\traverseDependencies.js:431:18)
    at D:\React Native\Pukaar-Community-Application\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\React Native\Pukaar-Community-Application\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)

 "react-native-agora": "^3.1.3"
 "react-native": "^0.63.1"

I tried using version 3.0.0 but it didn't work as well. The error stays the same

**Comment by LichKing-2234** [comment]
`AgoraView.native` is for the 2.x version. if you want to use the 3.x version, suggest you clean the `node_modules` folder, then run `npm install` and refer to our quickstart to learn how to use it.

**Comment by QasimJaffry** [comment]
> 
> 
> `AgoraView.native` is for the 2.x version. if you want to use the 3.x version, suggest you clean the `node_modules` folder, then run `npm install` and refer to our quickstart to learn how to use it.

Thank you for replying.

I did as you said but the error still remains.

**Comment by QasimJaffry** [comment]
Any suggestion?

**Comment by LichKing-2234** [comment]
maybe you can try to run `npm start -- --reset-cache`

**Comment by LichKing-2234** [comment]
https://stackoverflow.com/questions/46878638/how-to-clear-react-native-cache

**Comment by QasimJaffry** [comment]
Thank you. It is working now. What I did was android rebuilt project after npm install and then npm start -- --reset-cache.
