### ISSUE TITLE
App crash on release build Fatal Exception: java.lang.IllegalStateException: Incomplete hierarchy for class RtcEngineManager

### ISSUE THREAD

**Issue by zuhairnaqi** [AgoraIO-Community/react-native-agora#322]
App crash on release build while initializing call.
    "react-native": "0.62.2",
    "react-native-agora": "^3.2.2",

Firebase crashlytics report

`Fatal Exception: java.lang.IllegalStateException: Incomplete hierarchy for class RtcEngineManager, unresolved classes [io.agora.rtc.base.IRtcEngine$RtcEngineInterface]
       at kotlin.reflect.jvm.internal.components.RuntimeErrorReporter.reportIncompleteHierarchy(RuntimeErrorReporter.java:41)
       at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassTypeConstructor.computeSupertypes(DeserializedClassDescriptor.java:211)
       at kotlin.reflect.jvm.internal.impl.types.AbstractTypeConstructor$supertypes$1.invoke(AbstractTypeConstructor.java:4)
       at kotlin.reflect.jvm.internal.impl.types.AbstractTypeConstructor$supertypes$1.invoke(AbstractTypeConstructor.java)
       at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:86)
       at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java)
       at kotlin.reflect.jvm.internal.impl.types.AbstractTypeConstructor.getSupertypes(AbstractTypeConstructor.java:2)
       at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope.getNonDeclaredVariableNames(DeserializedClassDescriptor.java:8)
       at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$variableNamesLazy$2.invoke(DeserializedMemberScope.java:12)
       at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$variableNamesLazy$2.invoke(DeserializedMemberScope.java)
       at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:86)
       at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java)
       at kotlin.reflect.jvm.internal.impl.storage.StorageKt.getValue(StorageKt.java:10)
       at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope.getVariableNamesLazy(DeserializedMemberScope.java:7)
       at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope.getVariableNames(DeserializedMemberScope.java)
       at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope.addFunctionsAndProperties(DeserializedMemberScope.java:14)
       at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope.computeDescriptors(DeserializedMemberScope.java:36)
       at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope$allDescriptors$1.invoke(DeserializedClassDescriptor.java:12)
       at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope$allDescriptors$1.invoke(DeserializedClassDescriptor.java)
       at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:86)
       at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java)
       at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope.getContributedDescriptors(DeserializedClassDescriptor.java:12)
       at kotlin.reflect.jvm.internal.impl.resolve.scopes.ResolutionScope$DefaultImpls.getContributedDescriptors$default(ResolutionScope.java:18)
       at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.getMembers(KDeclarationContainerImpl.java:17)
       at kotlin.reflect.jvm.internal.KClassImpl$Data$declaredNonStaticMembers$2.invoke(KClassImpl.java:10)
       at kotlin.reflect.jvm.internal.KClassImpl$Data$declaredNonStaticMembers$2.invoke(KClassImpl.java)
       at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:17)
       at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java)
       at kotlin.reflect.jvm.internal.KClassImpl$Data.getDeclaredNonStaticMembers(KClassImpl.java:8)
       at kotlin.reflect.full.KClasses.getDeclaredMemberFunctions(KClasses.java:17)
       at io.agora.rtc.react.RCTAgoraRtcEngineModule.callMethod(RCTAgoraRtcEngineModule.java:15)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:149)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:21)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java)
       at android.os.Looper.loop(Looper.java:237)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:37)
       at java.lang.Thread.run(Thread.java:919)`

**Comment by LichKing-2234** [comment]
it seems like our `consumer-rules.pro` not working. you can try to add these rules to your `proguard-rules`
```
-keepattributes *Annotation*
-keep class kotlin.** { *; }
-keep class org.jetbrains.** { *; }

-keep class io.agora.**{*;}
```

**Comment by zuhairnaqi** [comment]
@LichKing-2234 I've added these to proguard-rules but not works.
Also just added a single line `-keep class io.agora.**{*;}` but not worked.

**Comment by zuhairnaqi** [comment]
Here is my proguard-rules.pro file, FYI we've also integrated twilio video webrtc.

`
-keep class org.webrtc.** { *; }
-keep class com.twilio.** { *; }
-keep class tvi.webrtc.** { *; }
-keepattributes *Annotation*
-keep class kotlin.** { *; }
-keep class org.jetbrains.** { *; }

-keep class io.agora.**{*;}

-keep public class com.horcrux.svg.** {*;}`

**Comment by LichKing-2234** [comment]
could you pls provide a demo? Then I will test it.

**Comment by rebirthtobi** [comment]
Also having this issue after running ./gradlew assembleRelease

```
/node_modules/react-native-agora/android/src/main/java/io/agora/rtc/base/RtcEngineEvent.kt: (268, 70): 'IntRange' is not an annotation class
e: /node_modules/react-native-agora/android/src/main/java/io/agora/rtc/base/RtcEngineEvent.kt: (268, 80): Cannot find a parameter with this name: from
e: /node_modules/react-native-agora/android/src/main/java/io/agora/rtc/base/RtcEngineEvent.kt: (268, 90): Cannot find a parameter with this name: to
e: /node_modules/react-native-agora/android/src/main/java/io/agora/rtc/base/RtcEngineEvent.kt: (268, 98): No value passed for parameter 'start'
e: /node_modules/react-native-agora/android/src/main/java/io/agora/rtc/base/RtcEngineEvent.kt: (268, 98): No value passed for parameter 'endInclusive'
```

**Comment by LichKing-2234** [comment]
you should make your project support AndroidX

**Comment by rebirthtobi** [comment]
Funny how it works now, steps

- rm -rf node_modules
- yarn install
- npx jetify (for some reason my post-install script is not working)
- Build

**Comment by zuhairnaqi** [comment]
@LichKing-2234 This setting works for me.
In build.gradle
`
buildTypes {
        ...
        release {
...
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
`
and
`def enableProguardInReleaseBuilds = false`

**Comment by rgommezz** [comment]
@zuhairnaqi I was able to reproduce the same issue on RN 0.63 with Proguard enabled.

It's a known Android problem as you can check [in their issue tracker](https://issuetracker.google.com/issues/169264693).

The kotlin metadata-processing in AGP 4.0 (R8 version 2.0) is not working correctly and the full support was added from AGP version 4.1 (R8 version 2.1). The solution for the time being is to enforce a specific R8 version in your `build.gradle` file:

```
buildscript {
    repositories {
        maven {
            url 'https://storage.googleapis.com/r8-releases/raw'
        }
    }

    dependencies {
        classpath 'com.android.tools:r8:2.1.75'          // Must be before the Gradle Plugin for Android.
        classpath 'com.android.tools.build:gradle:4.1.2' // Your current AGP version.
     }
}
```

That way, you can keep building for release mode without having to disable Proguard

**Comment by zuhairnaqi** [comment]
@rgommezz Thanks for commenting. I'll definitely try this.
