### ISSUE TITLE
parsing error

### ISSUE THREAD

**Issue by jeffersribeiro** [AgoraIO-Community/react-native-agora#324]
BUNDLE  [android, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1)::ffff:127.0.0.1 - - [12/Feb/2021:17:41:09 +0000] "GET /index.bundle?platform=android&dev=true&minify=false HTTP/1.1" 500 - "-" "okhttp/3.12.1"
error: bundling failed: SyntaxError: /home/jefferson/Documentos/dkp-projects/avivare/appavivare/node_modules/react-native-agora/src/common/RtcChannel.native.ts: Unexpected token (3:12)

  1 | import { NativeEventEmitter, NativeModules } from 'react-native';
  2 | 
> 3 | import type {
    |             ^
  4 |   ChannelMediaOptions,
  5 |   ChannelMediaRelayConfiguration,
  6 |   ClientRoleOptions,
    at Object.raise (/home/jefferson/Documentos/dkp-projects/avivare/appavivare/node_modules/@babel/parser/lib/index.js:6325:17)
    at Object.unexpected (/home/jefferson/Documentos/dkp-projects/avivare/appavivare/node_modules/@babel/parser/lib/index.js:7642:16)
    at Object.expectContextual (/home/jefferson/Documentos/dkp-projects/avivare/appavivare/node_modules/@babel/parser/lib/index.js:7608:41)
    at Object.parseImport (/home/jefferson/Documentos/dkp-projects/avivare/appavivare/node_modules/@babel/parser/lib/index.js:11168:12)
    at Object.parseImport (/home/jefferson/Documentos/dkp-projects/avivare/appavivare/node_modules/@babel/parser/lib/index.js:5316:18)
    at Object.parseStatementContent (/home/jefferson/Documentos/dkp-projects/avivare/appavivare/node_modules/@babel/parser/lib/index.js:9927:27)
    at Object.parseStatementContent (/home/jefferson/Documentos/dkp-projects/avivare/appavivare/node_modules/@babel/parser/lib/index.js:5372:18)
    at Object.parseStatement (/home/jefferson/Documentos/dkp-projects/avivare/appavivare/node_modules/@babel/parser/lib/index.js:9829:17)
    at Object.parseBlockOrModuleBlockBody (/home/jefferson/Documentos/dkp-projects/avivare/appavivare/node_modules/@babel/parser/lib/index.js:10405:25)
    at Object.parseBlockBody (/home/jefferson/Documentos/dkp-projects/avivare/appavivare/node_modules/@babel/parser/lib/index.js:10392:10)

**Comment by LichKing-2234** [comment]
pls refer to our [`metro.config.js`](https://github.com/AgoraIO-Community/react-native-agora/blob/master/example/metro.config.js) and [`tsconfig.json`](https://github.com/AgoraIO-Community/react-native-agora/blob/master/tsconfig.json)

**Comment by jeffersribeiro** [comment]
@LichKing-2234  my babel was out of date

**Comment by RafaelAlthaus** [comment]
@jeffersribeiro could you clarify what you did to fix it? I'm having the same problem. Already ran `npx babel-upgrade --write` and still the same.

**Comment by RoJoHub** [comment]
just 
`npm install  @babel/core  @babel/runtime -D`
