### ISSUE TITLE
RtcEngine.create() does not resolve on Android

### ISSUE THREAD

**Issue by zaiisao** [AgoraIO-Community/react-native-agora#361]
I do not have this problem on iOS, but this issue keeps persisting on Android. I have a wrapper component around most of the app that handles the RtcEngine, and the relevant portions are as follows:

```
function requestPermissionsIfOnAndroid() {
  return new Promise((resolve, reject) => {
    if (Platform === 'android') {
      try {
        PermissionsAndroid.requestMultiple(PERMISSIONS).then((granted) => {
          resolve(granted);
        }).catch((err) => {
          reject(err);
        });
      } catch (err) {
        reject(err);
      }
    } else {
      resolve(true);
    }
  });
}
```

```
requestPermissionsIfOnAndroid().then((granted) => {
  // This executes, concluded through console.log() statements
  // and the permissions window opening on my Android phone
  RtcEngine.create(APP_ID).then((engine) => {
    // This block never executes
    this.engine = engine;
    // ...
  });
});
```

I saw a similar issue #354 written and resolved relatively recently, but unfortunately that solution that the OP posted did not seem to work for me, and this issue happens both on my physical device and emulator.

**Comment by plutoless** [comment]
any errors in your logcat?

**Comment by zaiisao** [comment]
It looks to be this.

```
04-18 22:48:02.088 26888 31303 W System.err: java.lang.reflect.InvocationTargetException
04-18 22:48:02.088 26888 31303 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
04-18 22:48:02.088 26888 31303 W System.err: 	at io.agora.rtc.react.RCTAgoraRtcEngineModule.callMethod(RCTAgoraRtcEngineModule.kt:57)
04-18 22:48:02.088 26888 31303 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
04-18 22:48:02.088 26888 31303 W System.err: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
04-18 22:48:02.088 26888 31303 W System.err: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
04-18 22:48:02.088 26888 31303 W System.err: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
04-18 22:48:02.088 26888 31303 W System.err: 	at android.os.Handler.handleCallback(Handler.java:883)
04-18 22:48:02.088 26888 31303 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:100)
04-18 22:48:02.089 26888 31303 W System.err: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
04-18 22:48:02.089 26888 31303 W System.err: 	at android.os.Looper.loop(Looper.java:237)
04-18 22:48:02.089 26888 31303 W System.err: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
04-18 22:48:02.089 26888 31303 W System.err: 	at java.lang.Thread.run(Thread.java:919)
04-18 22:48:02.089 26888 31303 W System.err: Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.appname-E3SY1Xy09hhg8nY6u3GbsA==/base.apk"],nativeLibraryDirectories=[/data/app/com.appname-E3SY1Xy09hhg8nY6u3GbsA==/lib/arm64, /data/app/com.appname-E3SY1Xy09hhg8nY6u3GbsA==/base.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "libagora-ffmpeg.so"
04-18 22:48:02.089 26888 31303 W System.err: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
04-18 22:48:02.089 26888 31303 W System.err: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
04-18 22:48:02.089 26888 31303 W System.err: 	at java.lang.System.loadLibrary(System.java:1667)
04-18 22:48:02.089 26888 31303 W System.err: 	at io.agora.rtc.internal.RtcEngineImpl.loadNativeLibrary(RtcEngineImpl.java:163)
04-18 22:48:02.089 26888 31303 W System.err: 	at io.agora.rtc.internal.RtcEngineImpl.initializeNativeLibs(RtcEngineImpl.java:199)
04-18 22:48:02.090 26888 31303 W System.err: 	at io.agora.rtc.RtcEngine.create(RtcEngine.java:50)
04-18 22:48:02.090 26888 31303 W System.err: 	at io.agora.rtc.base.RtcEngineManager.create(RtcEngine.kt:368)
04-18 22:48:02.090 26888 31303 W System.err: 	... 12 more
04-18 22:48:02.566  4461  4598 E BufferQueueProducer: [com.appname/com.appname.MainActivity$_26888#1] disconnect: not connected (req=1)
```

**Comment by zaiisao** [comment]
@plutoless Would I be able to get some help on this? Really sorry as I understand you are probably quite busy, but this is a blocking issue for me and nothing I try works.

**Comment by LichKing-2234** [comment]
pls check your abi-filter. the error log shows couldn't find "libagora-ffmpeg.so"

**Comment by zaiisao** [comment]
@LichKing-2234 How do I do that? Google does not seem to give me any results.

**Comment by LichKing-2234** [comment]
the fast way is unzipping your .apk file, and find the .so files in the lib folder. pls make a screenshot of it.

**Comment by zaiisao** [comment]
There are four folders in here, and none of them have `libagora-ffmpeg.so` but they do have other .so files that start with `libagora`.

**Comment by zaiisao** [comment]
Ah, it looks like running `./gradlew clean` and `./gradlew bundle` does the trick. Thanks!

**Comment by duongquang1611** [comment]
I try clean cache by cmd ./gradlew clean, delete build folder android and build apk android then install app but RtcEngine still not working..

**Comment by LichKing-2234** [comment]
@duongquang1611 pls check error log in android logcat
